# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dox < Formula
  desc "Fetch library documentation files for AI agents and indexing tools"
  homepage "https://github.com/g5becks/dox"
  version "0.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/g5becks/dox/releases/download/v0.2.0/dox_Darwin_all.tar.gz"
    sha256 "e10bc4fb4ee5d4f4c5c68e85e9fc8e67260403815aaf23e77571deea1e80e6a8"

    def install
      bin.install "dox"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/g5becks/dox/releases/download/v0.2.0/dox_Linux_x86_64.tar.gz"
      sha256 "e3cb527ffcaa7ff4ff40440cf11d02984eee0fa488fc0593032a0b4dbf489c4a"
      def install
        bin.install "dox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/g5becks/dox/releases/download/v0.2.0/dox_Linux_arm64.tar.gz"
      sha256 "3f7e2391a5556a5da945bc7ad131ab6d04872ab30cbb707f1d811256bc71c4e3"
      def install
        bin.install "dox"
      end
    end
  end

  test do
    system "#{bin}/dox", "--version"
  end
end
