# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dox < Formula
  desc "Fetch library documentation files for AI agents and indexing tools"
  homepage "https://github.com/g5becks/dox"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/g5becks/dox/releases/download/v0.1.0/dox_Darwin_all.tar.gz"
    sha256 "06e15e8d179bb247376b584e37fec01f501b4e8d81bd2fa9df0e8744af1f931a"

    def install
      bin.install "dox"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/g5becks/dox/releases/download/v0.1.0/dox_Linux_x86_64.tar.gz"
      sha256 "e0bdf26d61b21f196b2876fd867a8be1e20d0d77b35d3cd0e78a1315bc248211"
      def install
        bin.install "dox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/g5becks/dox/releases/download/v0.1.0/dox_Linux_arm64.tar.gz"
      sha256 "674724c4a2a902af045e0b212108c50a05ba24858f5e3b10aec1078bb369f81e"
      def install
        bin.install "dox"
      end
    end
  end

  test do
    system "#{bin}/dox", "--version"
  end
end
